VKCOM/admstorm

- docs/faq.html
- docs/install.html
Fixed alignment for config on the install page.
> landing: added new q&a to faq

- src/main/kotlin/com/vk/admstorm/actions/git/PushToGitlabAction.kt
- src/main/kotlin/com/vk/admstorm/actions/git/checkout/GitCommitAndPushToAdmExecutorAction.kt
- src/main/kotlin/com/vk/admstorm/actions/git/checkout/GitCustomPushCheckinHandlerFactory.kt
- src/main/resources/META-INF/plugin.xml
The new push button pushes to the server and then shows the
gitlab push window. The functionality is the same as the
push button on the toolbar.
Fixes #16
> added a new push button in the dialog when creating a commit

- src/main/kotlin/com/vk/admstorm/executors/BaseRunnableExecutor.kt
- src/main/kotlin/com/vk/admstorm/executors/KphpRunExecutor.kt
- src/main/kotlin/com/vk/admstorm/executors/KphpScriptExecutor.kt
- src/main/kotlin/com/vk/admstorm/executors/PhpLinterExecutor.kt
- src/main/kotlin/com/vk/admstorm/executors/PushToRemoteExecutor.kt
- src/main/kotlin/com/vk/admstorm/executors/tabs/BaseTab.kt
- src/main/kotlin/com/vk/admstorm/executors/tabs/DiffTab.kt
- src/main/kotlin/com/vk/admstorm/executors/tabs/Tab.kt
Now they can't be closed.
Fixes #14
> refactored executor tabs

- src/main/kotlin/com/vk/admstorm/git/sync/files/FileSyncHandler.kt
- src/main/kotlin/com/vk/admstorm/utils/MyPathUtils.kt
> added fix for windows slashes

- src/main/kotlin/com/vk/admstorm/git/sync/files/FilesNotSyncDialog.kt
- src/main/kotlin/com/vk/admstorm/git/sync/files/RemoteFileManager.kt
- src/main/kotlin/com/vk/admstorm/transfer/TransferService.kt
- Now, when the user chooses to download a file, it starts
immediately without waiting for the dialog to close
- For files that are located only locally, the "remove from local" 
button has been added
- Fixed a bug where deleting a local file resulted in
replacing the content with "&lt;removed>" instead of
deleting it
- Fixed a bug when after deleting a file from the list,
the focus did not move to the next one
Fixes #27 
Fixes #25 
Fixes #24
> improved file synchronization dialog.

- src/main/kotlin/com/vk/admstorm/actions/CheckGitSyncAction.kt
- src/main/kotlin/com/vk/admstorm/actions/KphpPlaygroundAction.kt
- src/main/kotlin/com/vk/admstorm/actions/PlaygroundFromSelectionAction.kt
- src/main/kotlin/com/vk/admstorm/configuration/kphp/KphpScriptRunner.kt
- src/main/kotlin/com/vk/admstorm/console/Console.kt
- src/main/kotlin/com/vk/admstorm/executors/KphpScriptExecutor.kt
- src/main/kotlin/com/vk/admstorm/executors/tabs/DiffTab.kt
- src/main/kotlin/com/vk/admstorm/playground/KphpPhpDiffViewer.kt
- src/main/kotlin/com/vk/admstorm/playground/KphpPlaygroundWindow.kt
- src/main/kotlin/com/vk/admstorm/transfer/TransferService.kt
- src/main/kotlin/com/vk/admstorm/utils/MyUtils.kt
- src/main/resources/META-INF/plugin.xml
> added new KPHP Playground window

- src/main/resources/META-INF/plugin.xml
> fixed `ctrl+c` problem

- src/main/kotlin/com/vk/admstorm/actions/RunAnythingOnServerPopupUI.kt
- src/main/kotlin/com/vk/admstorm/configuration/WithSshConfigurationRunner.kt
- src/main/kotlin/com/vk/admstorm/configuration/php/RemotePhpConfiguration.kt
- src/main/kotlin/com/vk/admstorm/configuration/php/RemotePhpConfigurationEditor.form
- src/main/kotlin/com/vk/admstorm/configuration/php/RemotePhpConfigurationEditor.kt
- src/main/kotlin/com/vk/admstorm/configuration/php/RemotePhpConfigurationFactory.kt
- src/main/kotlin/com/vk/admstorm/configuration/php/RemotePhpConfigurationOptions.kt
- src/main/kotlin/com/vk/admstorm/configuration/php/RemotePhpConfigurationProducer.kt
- src/main/kotlin/com/vk/admstorm/configuration/php/RemotePhpConfigurationRunState.kt
- src/main/kotlin/com/vk/admstorm/configuration/php/RemotePhpConfigurationType.kt
- src/main/kotlin/com/vk/admstorm/configuration/php/RemotePhpRunner.kt
- src/main/kotlin/com/vk/admstorm/executors/KphpScriptExecutor.kt
- src/main/kotlin/com/vk/admstorm/executors/RemotePhpRunExecutor.kt
- src/main/kotlin/com/vk/admstorm/executors/tabs/BaseTab.kt
- src/main/kotlin/com/vk/admstorm/ssh/SshConnectionService.kt
- src/main/kotlin/com/vk/admstorm/utils/MyKphpUtils.kt
- src/main/kotlin/com/vk/admstorm/utils/MyPathUtils.kt
- src/main/kotlin/com/vk/admstorm/utils/MySshUtils.kt
- src/main/resources/META-INF/plugin.xml
> added initial PHP Debug configuration

- CHANGELOG.md
- src/main/kotlin/com/vk/admstorm/configuration/WithSshConfigurationRunner.kt
- src/main/kotlin/com/vk/admstorm/configuration/php/RemotePhpConfigurationRunState.kt
- src/main/kotlin/com/vk/admstorm/configuration/php/RemotePhpRunner.kt
- src/main/kotlin/com/vk/admstorm/configuration/phpunit/RemotePhpUnitConfiguration.kt
- src/main/kotlin/com/vk/admstorm/configuration/phpunit/RemotePhpUnitConfigurationProducer.kt
- src/main/kotlin/com/vk/admstorm/configuration/phpunit/RemotePhpUnitConfigurationRunState.kt
- src/main/kotlin/com/vk/admstorm/configuration/phpunit/RemotePhpUnitConfigurationRunner.kt
- src/main/kotlin/com/vk/admstorm/configuration/runanything/RunAnythingConfigurationRunner.kt
- src/main/kotlin/com/vk/admstorm/playground/KphpPlaygroundWindow.kt
- src/main/kotlin/com/vk/admstorm/utils/PhpDebugUtils.kt
- src/main/resources/META-INF/plugin.xml
- fixed a phpunit run configuration bug: when user starts class
test with gutter icon, plugin starts existing method test
instead
> added initial support of debug for phpunit tests

- CHANGELOG.md
- src/main/kotlin/com/vk/admstorm/actions/PlaygroundFromSelectionAction.kt
- src/main/kotlin/com/vk/admstorm/playground/KphpPlaygroundWindow.kt
- src/main/kotlin/com/vk/admstorm/psi/PhpRecursiveElementVisitor.kt
- src/main/resources/META-INF/plugin.xml
- "Execute Selected in Playground" action moved to top of list
Fixed #44
> added auto import classes for KPHP Playground

- src/main/kotlin/com/vk/admstorm/configuration/kbench/KBenchConfigurationRunState.kt
- src/main/kotlin/com/vk/admstorm/utils/MyPathUtils.kt
> added custom ktest bin path

- src/main/kotlin/com/vk/admstorm/ssh/YubikeyHandler.kt
> renamed `admstorm-yubikey-reset-script.sh` to `.admstorm-yubikey-reset-script.sh`

- src/main/kotlin/com/vk/admstorm/configuration/kbench/KBenchConfiguration.kt
- src/main/kotlin/com/vk/admstorm/configuration/kbench/KBenchConfigurationEditor.form
- src/main/kotlin/com/vk/admstorm/configuration/kbench/KBenchConfigurationEditor.kt
- src/main/kotlin/com/vk/admstorm/configuration/kbench/KBenchConfigurationLineMarkerProvider.kt
- src/main/kotlin/com/vk/admstorm/configuration/kbench/KBenchConfigurationOptions.kt
- src/main/kotlin/com/vk/admstorm/configuration/kbench/KBenchConfigurationProducer.kt
- src/main/kotlin/com/vk/admstorm/configuration/kbench/KBenchConfigurationRunState.kt
- src/main/kotlin/com/vk/admstorm/configuration/phpunit/RemotePhpUnitConfigurationEditor.kt
- src/main/kotlin/com/vk/admstorm/utils/KBenchUtils.kt
- Benchmark of a single class method
- Allocation benchmark for bench command
Fixed:
- Bug where bench-php could not be started due to the fact
that one of the flags is not supported by the command
- Bug when Line Marker was not installed on a leaf element,
which could lead to performance degradation
Fixes #62
> added new features of ktest

- src/main/kotlin/com/vk/admstorm/playground/KphpPlaygroundWindow.kt
> now after executing the script in KPHP Playground, users can see the compilation process

- CHANGELOG.md
- src/main/kotlin/com/vk/admstorm/actions/PlaygroundFromSelectionAction.kt
- src/main/kotlin/com/vk/admstorm/playground/KphpPlaygroundWindow.kt
- src/main/kotlin/com/vk/admstorm/services/YarnWatchService.kt
- src/main/kotlin/com/vk/admstorm/utils/MyUtils.kt
To do this, user need to click on the share button, after the
link is transferred to another user, it will be enough for
him to copy it to clipboard and click on the paste button.
Fixes #71
> added ability to share code from KPHP Playground

- src/main/kotlin/com/vk/admstorm/actions/DeployTestDomainAction.kt
- src/main/kotlin/com/vk/admstorm/configuration/kbench/KBenchConfigurationEditor.kt
- src/main/kotlin/com/vk/admstorm/env/Env.kt
- src/main/kotlin/com/vk/admstorm/executors/ActionToolbarPanel.kt
- src/main/kotlin/com/vk/admstorm/executors/BaseRunnableExecutor.kt
- src/main/kotlin/com/vk/admstorm/executors/DeployTestDomainExecutor.kt
- src/main/kotlin/com/vk/admstorm/services/DeployTestDomainService.kt
- src/main/kotlin/com/vk/admstorm/utils/MyUiUtils.kt
- src/main/resources/META-INF/plugin.xml
> added support for deploy test domains

- diktat-analysis.yml
- Enabled PACKAGE_NAME_INCORRECT_PATH
- DIKTAT_COMMON.domainName set to **com.vk.admstorm**
> Changed Diktat rules

- CHANGELOG.md
- gradle.properties
- src/main/kotlin/com/vk/admstorm/env/Env.kt
- src/main/kotlin/com/vk/admstorm/psi/references/JiraReferenceContributor.kt
- src/main/resources/META-INF/plugin.xml
> added recognize of Jira tickets in PHPDoc, JSDoc, and CSS comments

- CHANGELOG.md
- src/main/kotlin/com/vk/admstorm/utils/MyUtils.kt
- src/main/kotlin/com/vk/admstorm/utils/PhpDebugUtils.kt
> fixed a problem with opening SSH tunnels

- src/main/kotlin/com/vk/admstorm/configuration/kbench/KBenchImplicitTypeProvider.kt
- src/main/resources/META-INF/plugin.xml
> treat benchmark classes and methods as always implicit used

- CHANGELOG.md
- src/main/kotlin/com/vk/admstorm/AdmStormStartupActivity.kt
- src/main/kotlin/com/vk/admstorm/notifications/AdmNotification.kt
> added a welcome message for each plugin update

- src/main/kotlin/com/vk/admstorm/ui/YarnWatchStatusBarWidget.kt
- src/main/kotlin/com/vk/admstorm/ui/YarnWatchStatusBarWidgetFactory.kt
> hid yarn watch for non-vkcom projects

- src/main/kotlin/com/vk/admstorm/highlight/DebugLogLineMarkerProvider.kt
> fixed a performance issue for debug log line marker

- src/main/kotlin/com/vk/admstorm/git/GitUtils.kt
- src/main/kotlin/com/vk/admstorm/services/SentryService.kt
if it exists, if not, then global, if not, then null
> function for getting the current Git user now returns local data

- src/main/kotlin/com/vk/admstorm/configuration/php/PhpDebugUtils.kt
Also fixed recursive opening of SSH tunnels.
> fixed exception after automatically opening an SSH tunnel

- src/main/kotlin/com/vk/admstorm/configuration/phpunit/RemotePhpUnitConfigurationProducer.kt
> fixed run PHPUnit tests via context menu for a file

- src/main/kotlin/com/vk/admstorm/configuration/kbench/KBenchBaseConfigurationProducer.kt
- src/main/kotlin/com/vk/admstorm/configuration/kbench/KBenchImplicitUsageProvider.kt
- src/main/kotlin/com/vk/admstorm/configuration/kbench/KBenchUtils.kt
- src/main/resources/META-INF/plugin.xml
> added run ktest benchmarks via a context menu for a file

- src/main/kotlin/com/vk/admstorm/configuration/WithSshConfiguration.kt
- src/main/kotlin/com/vk/admstorm/configuration/WithSshConfigurationRunner.kt
- src/main/kotlin/com/vk/admstorm/configuration/kbench/KBenchConfigurationRunState.kt
- src/main/kotlin/com/vk/admstorm/configuration/kbench/KBenchConfigurationRunner.kt
- src/main/kotlin/com/vk/admstorm/configuration/php/RemotePhpConfiguration.kt
- src/main/kotlin/com/vk/admstorm/configuration/phpunit/RemotePhpUnitConfiguration.kt
- src/main/kotlin/com/vk/admstorm/configuration/runanything/RunAnythingConfiguration.kt
- src/main/resources/META-INF/plugin.xml
> fixed freeze when run ktest benchmarks

- src/main/kotlin/com/vk/admstorm/actions/CreateHasteAction.kt
- src/main/kotlin/com/vk/admstorm/configuration/WithSshConfigurationRunner.kt
- src/main/kotlin/com/vk/admstorm/configuration/builders/BuildersConfigurationRunState.kt
- src/main/kotlin/com/vk/admstorm/configuration/kphp/KphpConfigurationRunState.kt
- src/main/kotlin/com/vk/admstorm/configuration/kphp/KphpScriptRunner.kt
- src/main/kotlin/com/vk/admstorm/configuration/phplinter/PhpLinterConfigurationRunState.kt
- src/main/kotlin/com/vk/admstorm/executors/BaseRemoteExecutor.kt
- src/main/kotlin/com/vk/admstorm/executors/KphpScriptExecutor.kt
- src/main/kotlin/com/vk/admstorm/git/sync/files/RemoteFileManager.kt
- src/main/kotlin/com/vk/admstorm/playground/KphpPlaygroundWindow.kt
- src/main/kotlin/com/vk/admstorm/services/RunAnythingOnServerService.kt
- src/main/kotlin/com/vk/admstorm/services/YarnWatchService.kt
- src/main/kotlin/com/vk/admstorm/transfer/TransferService.kt
- src/main/kotlin/com/vk/admstorm/utils/MySshUtils.kt
- src/main/kotlin/com/vk/admstorm/utils/MyUtils.kt
> fixed a freeze when connection is lost and bug when mark yarn watch as running when connection is lost

- src/main/kotlin/com/vk/admstorm/AdmService.kt
- src/main/kotlin/com/vk/admstorm/AdmStormStartupActivity.kt
- src/main/kotlin/com/vk/admstorm/diagnostic/AdmStormLoggerFactory.kt
- src/main/kotlin/com/vk/admstorm/services/SentryService.kt
> added checking of new plugin version

- docs/faq.html
- docs/index.html
- docs/install.html
- docs/whatsnew.html
> replace 'kphp.me' -> 'kphp.dev' for images

- docs/css/index.css
- docs/index.html
- docs/whatsnew.html
Section "IDE instead of admin panels"
> landing for AdmStorm 2.0

- src/main/kotlin/com/vk/admstorm/services/SentryService.kt
More about `Internal Mode`: https://plugins.jetbrains.com/docs/intellij/enabling-internal.html
> disabled sending errors in development mode
